baseURL = "/" # 网站根目录
publishDir = "docs" # 打包目录
assetDir = "static" # 打包目录
title = "船长の部落格" # 网站标题
summaryLength = 10 # 文章缩略文本长度
paginate = 5 # 首页显示文章数量
enableEmoji = true # 允许使用 emoji
enableGitInfo = true # 允许使用 git 相关信息
disqusShortname = "daijiangtao-blog"

[author]
name = "CaptainOfPhB"

[params]
description = "船长の部落格" # 网站描述
enableSummary = true # 是否显示文章摘要
keywords = ["CaptainOfPhB", "船长の部落格"] # 网站关键字
mainSections = ["posts", "post"]
hasCJKLanguage = true # 自动检测中文、日文、韩文

[permalinks]
posts = "/:slug"
#posts = "/:year/:month/:day/:slug"

[markup.goldmark.renderer]
unsafe = true